//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareWare
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ShareWareEntities : DbContext
    {
        public ShareWareEntities()
            : base("name=ShareWareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FileInfo> FileInfo { get; set; }
        public DbSet<FileOwner> FileOwner { get; set; }
        public DbSet<Users> Users { get; set; }
    
        public virtual int InsertToFileInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertToFileInfo");
        }
    }
}
