//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareWare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.FileOwner = new HashSet<FileOwner>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public string Password { get; set; }
        public string UserIP { get; set; }
        public string MAC { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public bool IsMale { get; set; }
        public string QQ { get; set; }
        public string Mail { get; set; }
        public string MicroBlog { get; set; }
        public string Signature { get; set; }
        public string ImageHash { get; set; }
    
        public virtual ICollection<FileOwner> FileOwner { get; set; }
    }
}
